name: Deploy Backend

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /var/www/money/Etat_journalier
          git checkout production
          git pull origin production

      - name: Build and Restart Backend
        run: |
          cd /var/www/money/Etat_journalier
          pm2 restart fastapi-backend

      - name: Build Frontend
        run: |
          cd /var/www/money/Etat_journalier
          npm install
          npm run build